skinparam defaultFontName Noto Sans
skinparam defaultFontSize 13
skinparam defaultFontStyle bold
skinparam defaultFontColor #304158
skinparam dpi 300
skinparam nodesep 80
skinparam padding 10
skinparam ranksep 80
skinparam wrapWidth 400
skinparam maxMessageSize 150

hide stereotype

<style>
  element {
    FontColor #111111
    BackgroundColor #ffffff
    LineColor #333333
    BorderColor #333333
    LineThickness 2
    RoundCorner 0
    FontStyle normal
    Padding 2 50
  }

  rectangle {
    RoundCorner 15
  }

  file {
    TextAlignment left
  }

  legend {
    BackgroundColor #ffffff
    LineThickness 0
  }
</style>

skinparam Arrow {
  Color     #181818
  FontSize  11
  FontStyle normal
  Thickness 1.5
}
