# -*- org-confirm-babel-evaluate: nil -*-
#+OPTIONS: ^:nil
#+OPTIONS: html-postamble:nil
#+OPTIONS: num:3
#+LANGUAGE: en-us
#+HTML_DOCTYPE: html5
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/readtheorg.css"/>
#+HTML_HEAD: <style>blockquote p:last-child, div.figure p {margin: 0;}</style>
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,12pt]
#+LATEX_HEADER: \usepackage[english]{babel}
#+LATEX_HEADER: \renewcommand{\familydefault}{\sfdefault}
#+LATEX_HEADER: \usepackage{helvet}
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{tabularx}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[document]{ragged2e}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage{sectsty}
#+LATEX_HEADER: \titleformat*{\section}{\LARGE\bfseries}
#+LATEX_HEADER: \titleformat*{\subsection}{\Large\bfseries}
#+LATEX_HEADER: \titleformat*{\subsubsection}{\large\bfseries}
#+LATEX_HEADER: \titleformat*{\paragraph}{\large\bfseries}
#+LATEX_HEADER: \titleformat*{\subparagraph}{\large\bfseries}
#+LATEX_HEADER: \renewcommand{\baselinestretch}{1.2}
#+LATEX_HEADER: \definecolor{light_grey}{RGB}{51,51,51}
#+LATEX_HEADER: \definecolor{bright_grey}{RGB}{249,249,249}
#+LATEX_HEADER: \definecolor{python_blue}{RGB}{41,128,185}
#+LATEX_HEADER: \hypersetup{colorlinks=true, urlcolor=python_blue, linkcolor=python_blue, citecolor=red}
#+LATEX_HEADER: \tolerance=1
#+LATEX_HEADER: \emergencystretch=\maxdimen
#+LATEX_HEADER: \hyphenpenalty=10000
#+LATEX_HEADER: \hbadness=10000
#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \makeatother
#+LATEX_HEADER: \lstset{
#+LATEX_HEADER:   xleftmargin=0.5cm,frame=tlbr,framesep=4pt,framerule=0pt,
#+LATEX_HEADER:   columns=fullflexible,
#+LATEX_HEADER:   backgroundcolor=\color{white},
#+LATEX_HEADER:   basicstyle=\footnotesize\ttfamily,
#+LATEX_HEADER:   breakatwhitespace=false,
#+LATEX_HEADER:   breaklines=true,
#+LATEX_HEADER:   frame=single,
#+LATEX_HEADER:   keepspaces=true,
#+LATEX_HEADER:   rulecolor=\color{black},
#+LATEX_HEADER:   showspaces=false,
#+LATEX_HEADER:   showstringspaces=false,
#+LATEX_HEADER:   showtabs=false,
#+LATEX_HEADER:   stepnumber=2,
#+LATEX_HEADER:   tabsize=2,
#+LATEX_HEADER: }
#+LATEX_HEADER: \DeclareUnicodeCharacter{202F}{ }
#+LATEX: \frenchspacing
#+LATEX: \raggedright
#+TITLE: Guide: estimate heritability of disorder stratified by year of birth
#+AUTHOR: Richard Zetterberg <richard.zetterberg@regionh.dk>
#+PROPERTY: header-args:R :session *R* :tangle yes :shebang "#!/usr/bin/env Rscript"

#+LATEX: \clearpage

#+BEGIN_SRC R :exports none :tangle no
devtools::load_all(".")
source("./tests/utils.R")
#+END_SRC

#+RESULTS:

This is a guide for making the method in [[./guide.org]["estimate heritability of disorder"]] more robust
by adding year of birth stratification.

All code shown in this guide have been written to [[./guide-yob.R][this R file]], so that you don't have
to copy all code snippets manually.

We'll use all the same arguments and code as the previous guide, but we will start changing
the guide at the part where we produce the risk estimates.

We start by importing all the needed libraries:

#+BEGIN_SRC R :exports code :eval no
library(data.table)
library(dplyr)
library(dtplyr)
library(readr)
library(epimight)
#+END_SRC

#+BEGIN_SRC R :exports none
study_period_start <- as.Date("1981-01-01")
study_period_end   <- as.Date("2016-12-31")

icd_codes_regexp <- "^F20|^295[^7]9"
earliest_onset_age <- 10

born_at_start <- as.Date("1981-01-01")
born_at_end   <- as.Date("1996-01-01")

relationship_kind <- "FS"
#+END_SRC

#+RESULTS:
: FS

#+BEGIN_SRC R :eval no :exports code
tte <- read_csv("./tte_SCZ_FS.csv") |> as.data.table()
#+END_SRC

#+BEGIN_SRC R :exports results :results output :tangle no
set.seed(6)
n_count <- 100000

tte <- generate_random_tte(n_count)
tte <- generate_failure(tte, 20, 10)
tte <- generate_diagnosed_relatives(tte, "diagnosed_relatives") |>
  select(-born_at_year, -dead_at_year) |>
  relocate(relatives, .after = failure_time) |>
  as.data.table()
#+END_SRC

#+RESULTS:

#+BEGIN_SRC R :exports both :results output
tte <- tte |>
  filter(
    born_at >= born_at_start,
    born_at <= born_at_end
  )
#+END_SRC

#+RESULTS:

#+BEGIN_SRC R :exports both :results output
print(tte)
#+END_SRC

#+RESULTS:
#+begin_example
       person_id gender    born_at failure_status failure_time relatives
    1:         4      f 1986-03-12              0           40         4
    2:         5      f 1990-10-10              0           36         1
    3:         9      m 1993-11-17              0           33         4
    4:        12      f 1992-04-02              0           34         3
    5:        33      m 1993-10-30              0           33         4
   ---
19828:     99971      m 1994-08-08              0           32         3
19829:     99973      m 1993-07-15              0           33         2
19830:     99975      f 1986-04-05              0           40         0
19831:     99990      m 1981-08-04              0           45         3
19832:     99992      f 1982-12-25              0           44         1
       diagnosed_relatives
    1:                   0
    2:                   1
    3:                   0
    4:                   0
    5:                   0
   ---
19828:                   0
19829:                   0
19830:                   0
19831:                   3
19832:                   0
#+end_example

* Analysis

** Risk estimates

#+BEGIN_SRC R :exports none
cif_analysis <- CumulativeIncidenceAnalysis$new()
#+END_SRC

#+RESULTS:

In this updated version of the pipeline, we are going to use the same two cohorts
as the original version:

1. All individuals
2. Individuals with at least 1 affected relative

In the original version of the pipeline, the results looked something like this:

#+BEGIN_EXAMPLE
    time   estimate     variance        l95        u95 cases             cohort
 1:   10 0.05769079 2.261547e-04 0.02821599 0.08716559     1 affected_relatives
 2:   11 0.06229293 2.451218e-04 0.03160702 0.09297885     2 affected_relatives
27:   10 0.02128324 2.227802e-05 0.01203229 0.03053419     1                all
28:   11 0.02250389 2.371205e-05 0.01295984 0.03204794     3                all
#+END_EXAMPLE

Where you have risk estimates separated on the two cohorts. In this updated version,
the results will look something like this:

#+BEGIN_EXAMPLE
    time   estimate     variance        l95        u95 cases             cohort  born_at_year
 1:   10 0.05769079 2.261547e-04 0.02821599 0.08716559     1 affected_relatives          1960
 2:   11 0.06229293 2.451218e-04 0.03160702 0.09297885     2 affected_relatives          1960
27:   10 0.02128324 2.227802e-05 0.01203229 0.03053419     1                all          1960
28:   11 0.02250389 2.371205e-05 0.01295984 0.03204794     3                all          1960
 1:   10 0.05769079 2.261547e-04 0.02821599 0.08716559     1 affected_relatives          1961
 3:   12 0.06696774 2.645270e-04 0.03509033 0.09884516     3 affected_relatives          1961
27:   10 0.02128324 2.227802e-05 0.01203229 0.03053419     1                all          1961
29:   12 0.02497864 2.664947e-05 0.01486069 0.03509659     4                all          1961
 1:   10 0.05769079 2.261547e-04 0.02821599 0.08716559     1 affected_relatives          1962
 3:   12 0.06696774 2.645270e-04 0.03509033 0.09884516     3 affected_relatives          1962
27:   10 0.02128324 2.227802e-05 0.01203229 0.03053419     1                all          1962
29:   12 0.02497864 2.664947e-05 0.01486069 0.03509659     4                all          1962
#+END_EXAMPLE

Where you have risk estimates separated on the two cohorts and the year of birth.

To pull that of, we simply add a new column that contains the year of birth:

#+BEGIN_SRC R :exports code :results output
tte <- tte |>
  mutate(
    born_at_year = as.character(format(born_at, "%Y"))
  )
#+END_SRC

#+RESULTS:

And then like before, we create the two cohorts:

#+BEGIN_SRC R :exports code :results output
tte <- tte |>
  mutate(cohort = "all") |>
  union_all(
    tte |>
      filter(diagnosed_relatives > 0) |>
      mutate(cohort = "affected_relatives")
  )
#+END_SRC

#+RESULTS:

Now the survival data have the same amount of rows as before, but with one extra column added:

#+BEGIN_SRC R :exports both :results output
print(tte)
#+END_SRC

#+RESULTS:
#+begin_example
       person_id gender    born_at failure_status failure_time relatives
    1:         4      f 1986-03-12              0           40         4
    2:         5      f 1990-10-10              0           36         1
    3:         9      m 1993-11-17              0           33         4
    4:        12      f 1992-04-02              0           34         3
    5:        33      m 1993-10-30              0           33         4
   ---
24320:     99957      f 1989-02-09              0           37         3
24321:     99960      f 1988-02-10              0           38         2
24322:     99964      m 1993-02-02              0           33         3
24323:     99965      f 1995-10-27              0           31         4
24324:     99990      m 1981-08-04              0           45         3
       diagnosed_relatives born_at_year             cohort
    1:                   0         1986                all
    2:                   1         1990                all
    3:                   0         1993                all
    4:                   0         1992                all
    5:                   0         1993                all
   ---
24320:                   3         1989 affected_relatives
24321:                   1         1988 affected_relatives
24322:                   3         1993 affected_relatives
24323:                   1         1995 affected_relatives
24324:                   3         1981 affected_relatives
#+end_example

Now when we run the analysis, we supply *both* the ~affected_relatives~ column and the
~born_at_year~ column:

#+BEGIN_SRC R :exports code :results output
estimates <- cif_analysis$run(
  tte = tte,
  earliest_onset_age = earliest_onset_age,
  stratify_columns = list("born_at_year", "cohort")
)
#+END_SRC

#+RESULTS:

Now, you'll see that the estimates are grouped on all the possible permutations of the
two columns:

#+BEGIN_SRC R :exports both :results output
print(estimates)
#+END_SRC

#+RESULTS:
#+begin_example
     time    estimate     variance           l95        u95 cases born_at_year
  1:    2 0.006557377 2.142887e-05 -0.0025155574 0.01563031     2         1981
  2:    5 0.013114754 4.257532e-05  0.0003260342 0.02590347     5         1981
  3:    6 0.022950820 7.376528e-05  0.0061173331 0.03978431     6         1981
  4:    8 0.026229508 8.402084e-05  0.0082639138 0.04419510     7         1981
  5:   10 0.029508197 9.420579e-05  0.0104848515 0.04853154     8         1981
 ---
915:   27 0.080152672 5.632586e-05  0.0654430332 0.09486231   108         1995
916:   28 0.083969466 5.876330e-05  0.0689449261 0.09899401   112         1995
917:   29 0.087022901 6.069723e-05  0.0717531297 0.10229267   117         1995
918:   30 0.090839695 6.309462e-05  0.0752712849 0.10640810   119         1995
919:   31 0.092366412 6.404735e-05  0.0766809016 0.10805192   134         1995
                 cohort
  1: affected_relatives
  2: affected_relatives
  3: affected_relatives
  4: affected_relatives
  5: affected_relatives
 ---
915:                all
916:                all
917:                all
918:                all
919:                all
#+end_example

** Heritability

After producing the risk estimates, we can calculate the heritability.
To do that we need a dataset that contains the last risk estimate
(highest value of ~time~ column) for each year of birth, that exists
in both cohorts:

#+BEGIN_SRC R :exports both :results output
cohort1 <- estimates |> filter(cohort == "all")
cohort2 <- estimates |> filter(cohort == "affected_relatives")
#+END_SRC

#+RESULTS:

Then to make sure we only use risk estimates that exists in both cohorts, we
join the two cohorts using an inner join. An inner join will only keep rows that
have matches in both datasets, all other rows are removed. Since the results are
stratified by year of birth, we need to make sure the risk estimates exists in both
cohorts, for all years:

#+BEGIN_SRC R :exports both :results output
combined <- cohort1 |>
  inner_join(cohort2, by = join_by(time, born_at_year)) |>
  rename(
    c1_estimate = estimate.x,
    c1_cases    = cases.x,
    c2_estimate = estimate.y,
    c2_cases    = cases.y
  ) |>
  select(time, born_at_year, c1_estimate, c1_cases, c2_estimate, c2_cases)
#+END_SRC

#+RESULTS:

Now we have a combined dataset where each row represents risk estimates from both cohorts.
Since we are only interested in the last risk estimate in each year of birth, we need to
sort the risk estimates so that the last risk estimate is first and then pick the first
risk estimate per year of birth:

#+BEGIN_SRC R :exports both :results output
combined <- combined |>
  group_by(born_at_year) |>
  arrange(desc(time)) |>
  filter(row_number() == 1) |>
  as.data.table()
#+END_SRC

#+RESULTS:

If we order the dataset by year of birth, we can see that we have the latest
risk estimate for each year with the estimates and amount of cases for
both cohorts:

#+BEGIN_SRC R :exports both :results output
print(combined |> arrange(born_at_year))
#+END_SRC

#+RESULTS:
#+begin_example
    time born_at_year c1_estimate c1_cases c2_estimate c2_cases
 1:   45         1981  0.10323575      130   0.1803279       53
 2:   44         1982  0.09173616      120   0.1749175       53
 3:   43         1983  0.09552691      126   0.1818182       49
 4:   42         1984  0.10204082      140   0.2335526       71
 5:   41         1985  0.09273570      123   0.1626298       49
 6:   40         1986  0.08796296      108   0.1575563       46
 7:   39         1987  0.09696521      131   0.1902985       53
 8:   38         1988  0.09925926      136   0.2040134       59
 9:   37         1989  0.08771930      123   0.1975309       68
10:   36         1990  0.08728367      120   0.1692790       55
11:   35         1991  0.09274495      132   0.1707317       55
12:   34         1992  0.10872894      153   0.2165605       73
13:   33         1993  0.10047468      144   0.2194245       67
14:   32         1994  0.08897338      122   0.1655405       53
15:   31         1995  0.09236641      134   0.2006270       70
#+end_example

Now we can simply run the heritability calculation by passing in the the estimate and
cases columns from the combined dataset along with the relationship kind:

#+BEGIN_SRC R :exports both :results output
h2_analysis <- HeritabilityAnalysis$new()

h2_estimates <- h2_analysis$run(
  relationship_kind = relationship_kind,
  estimates         = combined
) |> select(time, born_at_year, estimate, se, l95, u95) # We don't need the risk estimate columns
#+END_SRC

#+RESULTS:

And here's what the results look like:

#+BEGIN_SRC R :exports both :results output
print(h2_estimates)
#+END_SRC

#+RESULTS:
#+begin_example
    time born_at_year  estimate         se       l95       u95
 1:   45         1981 0.4208978 0.10808121 0.2090587 0.6327370
 2:   44         1982 0.4639312 0.10388990 0.2603070 0.6675554
 3:   43         1983 0.4733527 0.10904459 0.2596254 0.6870801
 4:   42         1984 0.6606013 0.09848959 0.4675617 0.8536409
 5:   41         1985 0.3986083 0.10640262 0.1900592 0.6071574
 6:   40         1986 0.4034575 0.10800697 0.1917638 0.6151511
 7:   39         1987 0.5037650 0.10646806 0.2950876 0.7124424
 8:   38         1988 0.5516041 0.10341720 0.3489064 0.7543019
 9:   37         1989 0.5903352 0.09368178 0.4067189 0.7739515
10:   36         1990 0.4647303 0.10012014 0.2684948 0.6609658
11:   35         1991 0.4378898 0.10151138 0.2389275 0.6368521
12:   34         1992 0.5535345 0.09773931 0.3619655 0.7451036
13:   33         1993 0.6108216 0.09914830 0.4164909 0.8051522
14:   32         1994 0.4362322 0.10186895 0.2365690 0.6358953
15:   31         1995 0.5764495 0.09374994 0.3926997 0.7601994
#+end_example

Since the results are stratified by year of birth, we need to run a meta
analysis to get a single value:

#+BEGIN_SRC R :exports both :results output
meta <- h2_analysis$run_meta(
  estimates       = h2_estimates,
  estimate_column = "estimate",
  se_column       = "se"
)

print(meta)
#+END_SRC

#+RESULTS:
: fixed_meta   fixed_se fixed_l95 fixed_u95 rand_meta    rand_se  rand_l95  rand_u95
: 1:  0.5084953 0.02627478 0.4569967 0.5599938 0.5063277 0.03380745 0.4400651 0.5725903

There are actually two results one for the fixed effects model and one for the random effects model.

The next logical step is to use the [[../genetic-correlation/guide.org][estimate genetic correlation between two disorders]]-pipeline,
since that pipeline builds upon the results of this pipeline.
