# -*- org-confirm-babel-evaluate: nil -*-
#+OPTIONS: ^:nil
#+OPTIONS: html-postamble:nil
#+OPTIONS: num:3
#+LANGUAGE: en-us
#+HTML_DOCTYPE: html5
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/readtheorg.css"/>
#+HTML_HEAD: <style>blockquote p:last-child, div.figure p {margin: 0;}</style>
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,12pt]
#+LATEX_HEADER: \usepackage[english]{babel}
#+LATEX_HEADER: \renewcommand{\familydefault}{\sfdefault}
#+LATEX_HEADER: \usepackage{helvet}
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{tabularx}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[document]{ragged2e}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage{sectsty}
#+LATEX_HEADER: \titleformat*{\section}{\LARGE\bfseries}
#+LATEX_HEADER: \titleformat*{\subsection}{\Large\bfseries}
#+LATEX_HEADER: \titleformat*{\subsubsection}{\large\bfseries}
#+LATEX_HEADER: \titleformat*{\paragraph}{\large\bfseries}
#+LATEX_HEADER: \titleformat*{\subparagraph}{\large\bfseries}
#+LATEX_HEADER: \renewcommand{\baselinestretch}{1.2}
#+LATEX_HEADER: \definecolor{light_grey}{RGB}{51,51,51}
#+LATEX_HEADER: \definecolor{bright_grey}{RGB}{249,249,249}
#+LATEX_HEADER: \definecolor{python_blue}{RGB}{41,128,185}
#+LATEX_HEADER: \hypersetup{colorlinks=true, urlcolor=python_blue, linkcolor=python_blue, citecolor=red}
#+LATEX_HEADER: \tolerance=1
#+LATEX_HEADER: \emergencystretch=\maxdimen
#+LATEX_HEADER: \hyphenpenalty=10000
#+LATEX_HEADER: \hbadness=10000
#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \makeatother
#+LATEX_HEADER: \lstset{
#+LATEX_HEADER:   xleftmargin=0.5cm,frame=tlbr,framesep=4pt,framerule=0pt,
#+LATEX_HEADER:   columns=fullflexible,
#+LATEX_HEADER:   backgroundcolor=\color{white},
#+LATEX_HEADER:   basicstyle=\footnotesize\ttfamily,
#+LATEX_HEADER:   breakatwhitespace=false,
#+LATEX_HEADER:   breaklines=true,
#+LATEX_HEADER:   frame=single,
#+LATEX_HEADER:   keepspaces=true,
#+LATEX_HEADER:   rulecolor=\color{black},
#+LATEX_HEADER:   showspaces=false,
#+LATEX_HEADER:   showstringspaces=false,
#+LATEX_HEADER:   showtabs=false,
#+LATEX_HEADER:   stepnumber=2,
#+LATEX_HEADER:   tabsize=2,
#+LATEX_HEADER: }
#+LATEX_HEADER: \DeclareUnicodeCharacter{202F}{ }
#+LATEX: \frenchspacing
#+LATEX: \raggedright
#+TITLE: Guide: running the pipeline
#+AUTHOR: Richard Zetterberg <richard.zetterberg@regionh.dk>
#+PROPERTY: header-args:R :session *R* :tangle yes :shebang "#!/usr/bin/env Rscript"

#+LATEX: \clearpage

#+BEGIN_SRC R :exports none :tangle no
devtools::load_all(".")
source("./tests/utils.R")
#+END_SRC

#+BEGIN_SRC R :exports results :results output :tangle no
#set.seed(6)
#n_count <- 10000
#
#d1_tte <- generate_random_tte(n_count)
#d1_tte <- generate_failure(d1_tte, 20, 10)
#d1_tte <- generate_diagnosed_relatives(d1_tte, "relatives_diagnosed") |>
#  relocate(failure_time, .after = person_id) |>
#  relocate(failure_status, .after = failure_time) |>
#  relocate(relatives, .after = failure_status) |>
#  relocate(relatives_diagnosed, .after = relatives) |>
#  mutate(person_id = as.character(person_id), disorder = "SCZ", relationship_kind = "FS") |>
#  as.data.table()
#
#d2_tte <- copy(d1_tte |> select(-failure_time, -failure_status, -relatives_diagnosed, -disorder, -relationship_kind))
#d2_tte <- generate_failure(d2_tte, 19, 11)
#d2_tte <- generate_diagnosed_relatives(d2_tte, "relatives_diagnosed") |>
#  relocate(failure_time, .after = person_id) |>
#  relocate(failure_status, .after = failure_time) |>
#  relocate(relatives, .after = failure_status) |>
#  relocate(relatives_diagnosed, .after = relatives) |>
#  mutate(person_id = as.character(person_id), disorder = "CAD", relationship_kind = "FS") |>
#  as.data.table()
#
#d3_tte <- copy(d1_tte |> select(-failure_time, -failure_status, -relatives_diagnosed, -disorder, -relationship_kind))
#d3_tte <- generate_failure(d2_tte, 20, 10)
#d3_tte <- generate_diagnosed_relatives(d2_tte, "relatives_diagnosed") |>
#  relocate(failure_time, .after = person_id) |>
#  relocate(failure_status, .after = failure_time) |>
#  relocate(relatives, .after = failure_status) |>
#  relocate(relatives_diagnosed, .after = relatives) |>
#  mutate(person_id = as.character(person_id), disorder = "SCZ", relationship_kind = "PO") |>
#  as.data.table()
#
#d4_tte <- copy(d1_tte |> select(-failure_time, -failure_status, -relatives_diagnosed, -disorder, -relationship_kind))
#d4_tte <- generate_failure(d2_tte, 19, 11)
#d4_tte <- generate_diagnosed_relatives(d2_tte, "relatives_diagnosed") |>
#  relocate(failure_time, .after = person_id) |>
#  relocate(failure_status, .after = failure_time) |>
#  relocate(relatives, .after = failure_status) |>
#  relocate(relatives_diagnosed, .after = relatives) |>
#  mutate(person_id = as.character(person_id), disorder = "CAD", relationship_kind = "PO") |>
#  as.data.table()
#
#tte <- rbindlist(list(d1_tte, d2_tte, d3_tte, d4_tte)) |> select(-born_at, -dead_at_year) |>
#  arrange(person_id, disorder, relationship_kind) |>
#  select(person_id, born_at_year, gender, disorder, failure_status, failure_time, relationship_kind, relatives, relatives_diagnosed)
#
#write_csv(tte, "./guides/data/tte-pool.csv")

tte <- read_csv(
  "./guides/data/tte-pool.csv",
  show_col_type = FALSE,
  col_types=cols(person_id = col_character()),
)
#+END_SRC

#+RESULTS:

This is a guide that explains how you run the epimight pipeline to estimates genetic
correlation between 2 disorders stratified by birth year and gender using TTE (time-to-event) data.

All code shown in this guide have been written to [[./guide.R][this R file]], so that you don't have
to copy all code snippets manually.

* How it works

The concept is pretty simple:

1. Create a pool of time-to-event data
2. Create a new pipeline instance from said pool
3. Run trails by supplying the disorders and relationship kind to test

The idea here is that your "pool" contains time-to-event data for multiple disorders and relationship kinds.
Then when you run a trail, you specify exactly which disorders and relationship kind to use.

For example, say that your pool contains time-to-event data for the 10 most common mental disorders
for siblings and cousins. Here's what 3 trails could look like that uses this pool of data:

- Trail 1
  - Disorder 1 :: Schizophrenia
  - Disorder 2 :: MDD
  - Relationship kind :: Siblings
- Trail 2
  - Disorder 1 :: Schizophrenia
  - Disorder 2 :: MDD
  - Relationship kind :: Cousins
- Trail 3
  - Disorder 1 :: Schizophrenia
  - Disorder 2 :: ADHD
  - Relationship kind :: Siblings

By having all the time-to-event data in a big pool and letting the trails pull from this pool minimizes
data handling between trails.

Besides controlling what disorder and relationship kind to use for each trail, you can specify which columns
to stratify the results on and how many independent draws to perform. We'll get into the details of how trails
are carried out later. First we need to understand to just get the pipeline running.

* Setting up the pool

First we need to be able to uniquely identify every individual in your sample population.
In the test data of this guide we use a unique number for each individual:

#+BEGIN_SRC R :exports results :results value :colnames yes :tangle no
tte |> select(person_id) |> tail(4)
#+END_SRC

#+RESULTS:
| person_id |
|-----------|
|      9999 |
|      9999 |
|      9999 |
|      9999 |

Then we need to have the stratification data of each individual (in our case, birth year and gender):

#+BEGIN_SRC R :exports results :results value :colnames yes :tangle no
tte |>
  distinct(person_id, born_at_year, gender) |>
  tail(4)
#+END_SRC

#+RESULTS:
| person_id | born_at_year | gender |
|-----------+--------------+--------|
|      9996 |         2001 | m      |
|      9997 |         1999 | m      |
|      9998 |         2010 | m      |
|      9999 |         1991 | f      |

Then for each relationship kind, we need to know how many relatives each individual has. In the test data
of this guide, we have 2 relationship kinds (~PO~ = "parent offspring", ~FS~ = "full siblings"):

#+BEGIN_SRC R :exports results :results value :colnames yes :tangle no
tte |>
  distinct(person_id, born_at_year, gender, relationship_kind, relatives) |>
  tail(4)
#+END_SRC

#+RESULTS:
| person_id | born_at_year | gender | relationship_kind | relatives |
|-----------+--------------+--------+-------------------+-----------|
|      9998 |         2010 | m      | FS                |         0 |
|      9998 |         2010 | m      | PO                |         0 |
|      9999 |         1991 | f      | FS                |         1 |
|      9999 |         1991 | f      | PO                |         1 |

Then for each disorder, we to know:

- The individuals failure status/time
- The relatives diagnosis status

Since this test data has:

- 2 disorders (~SCZ~ = "schizophrenia", ~CAD~ = "coronary artery disease")
- 2 relationship kinds (~PO~, ~FS~)

Each individual gets 4 rows to cover all combinations of disorders x relationship kinds:

#+BEGIN_SRC R :exports results :results value :colnames yes :tangle no
tte |>
  tail(4)
#+END_SRC

#+RESULTS:
| person_id | born_at_year | gender | disorder | failure_status | failure_time | relationship_kind | relatives | relatives_diagnosed |
|-----------+--------------+--------+----------+----------------+--------------+-------------------+-----------+---------------------|
|      9999 |         1991 | f      | CAD      |              0 |           35 | FS                |         1 |                   0 |
|      9999 |         1991 | f      | CAD      |              0 |           35 | PO                |         1 |                   0 |
|      9999 |         1991 | f      | SCZ      |              0 |           35 | FS                |         1 |                   0 |
|      9999 |         1991 | f      | SCZ      |              0 |           35 | PO                |         1 |                   0 |

* asd


To avoid confusion the following naming convention will be used:

- Disorders:
  - ~d1~ = Schizophrenia
  - ~d2~ = Coronary Artery Disease
- Cohorts:
  - ~c1~ = Target cohort
  - ~c2~ = Individuals with at least 1 relative diagnosed with disorder 1
  - ~c3~ = Individuals with at least 1 relative diagnosed with disorder 2
- Results:
  - ~re_d1_c1~ = Risk estimates of disorder 1, cohort 1
  - ~re_d1_c2~ = Risk estimates of disorder 1, cohort 2
  - ~re_d1_c3~ = Risk estimates of disorder 1, cohort 3
  - ~re_d2_c1~ = Risk estimates of disorder 2, cohort 1
  - ~re_d2_c3~ = Risk estimates of disorder 2, cohort 3
  - ~h2_d1~ = Heritability of disorder 1 (cohort 1 vs cohort 2)
  - ~h2_d2~ = Heritability of disorder 2 (cohort 1 vs cohort 3)
  - ~gc_d1_d2~ = Genetic correlation (disorder 1 vs disorder 2)

We start by importing all the needed libraries:

#+BEGIN_SRC R :exports code :eval no
library(data.table)
library(dplyr)
library(dtplyr)
library(readr)
library(epimight)
#+END_SRC
