# -*- org-confirm-babel-evaluate: nil -*-
#+OPTIONS: ^:nil
#+OPTIONS: html-postamble:nil
#+OPTIONS: num:3
#+LANGUAGE: en-us
#+HTML_DOCTYPE: html5
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/readtheorg.css"/>
#+HTML_HEAD: <style>blockquote p:last-child, div.figure p {margin: 0;}</style>
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,12pt]
#+LATEX_HEADER: \usepackage[english]{babel}
#+LATEX_HEADER: \renewcommand{\familydefault}{\sfdefault}
#+LATEX_HEADER: \usepackage{helvet}
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{tabularx}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[document]{ragged2e}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage{sectsty}
#+LATEX_HEADER: \titleformat*{\section}{\LARGE\bfseries}
#+LATEX_HEADER: \titleformat*{\subsection}{\Large\bfseries}
#+LATEX_HEADER: \titleformat*{\subsubsection}{\large\bfseries}
#+LATEX_HEADER: \titleformat*{\paragraph}{\large\bfseries}
#+LATEX_HEADER: \titleformat*{\subparagraph}{\large\bfseries}
#+LATEX_HEADER: \renewcommand{\baselinestretch}{1.2}
#+LATEX_HEADER: \definecolor{light_grey}{RGB}{51,51,51}
#+LATEX_HEADER: \definecolor{bright_grey}{RGB}{249,249,249}
#+LATEX_HEADER: \definecolor{python_blue}{RGB}{41,128,185}
#+LATEX_HEADER: \hypersetup{colorlinks=true, urlcolor=python_blue, linkcolor=python_blue, citecolor=red}
#+LATEX_HEADER: \tolerance=1
#+LATEX_HEADER: \emergencystretch=\maxdimen
#+LATEX_HEADER: \hyphenpenalty=10000
#+LATEX_HEADER: \hbadness=10000
#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \makeatother
#+LATEX_HEADER: \lstset{
#+LATEX_HEADER:   xleftmargin=0.5cm,frame=tlbr,framesep=4pt,framerule=0pt,
#+LATEX_HEADER:   columns=fullflexible,
#+LATEX_HEADER:   backgroundcolor=\color{white},
#+LATEX_HEADER:   basicstyle=\footnotesize\ttfamily,
#+LATEX_HEADER:   breakatwhitespace=false,
#+LATEX_HEADER:   breaklines=true,
#+LATEX_HEADER:   frame=single,
#+LATEX_HEADER:   keepspaces=true,
#+LATEX_HEADER:   rulecolor=\color{black},
#+LATEX_HEADER:   showspaces=false,
#+LATEX_HEADER:   showstringspaces=false,
#+LATEX_HEADER:   showtabs=false,
#+LATEX_HEADER:   stepnumber=2,
#+LATEX_HEADER:   tabsize=2,
#+LATEX_HEADER: }
#+LATEX_HEADER: \DeclareUnicodeCharacter{202F}{ }
#+LATEX: \frenchspacing
#+LATEX: \raggedright
#+TITLE: Guide: estimate cumulative incidence of disorder
#+AUTHOR: Richard Zetterberg <richard.zetterberg@regionh.dk>
#+PROPERTY: header-args:R :session *R* :tangle yes :shebang "#!/usr/bin/env Rscript"

#+LATEX: \clearpage

#+BEGIN_SRC R :exports none :tangle no
devtools::load_all(".")
source("./tests/utils.R")
#+END_SRC

#+RESULTS:

This is a guide for estimating cumulative incidence risk estimates of a single
disorder from TTE data.

All code shown in this guide have been written to [[./guide.R][this R file]], so that you don't have
to copy all code snippets manually.

There are 3 different things you can configure when running this pipeline:

- Study period
- Disorder to study
- Cohort to estimate the risk in

In this guide we are going to answer the following research question:
"What is the lifetime risk of schizophrenia in Danish millenials (born between 1981 and 1996)?"

We start by importing all the needed libraries:

#+BEGIN_SRC R :exports code :eval no
library(data.table)
library(dplyr)
library(dtplyr)
library(readr)
library(epimight)
#+END_SRC

* Arguments

** Study period

The first thing we need to do is to define the arguments that reflects the research question.
Since we want to study millenials, we will use the millenials start year as the start year of
the study:

#+BEGIN_SRC R :exports code
# Arguments for research question:
# What is the lifetime risk of schizophrenia in millenials (people born from 1981 to 1996)?

study_period_start <- as.Date("1981-01-01")
study_period_end   <- as.Date("2016-12-31")
#+END_SRC

#+RESULTS:
: 2016-12-31

The reason why we use ~2016-12-31~ as the end date, is because the registry data in the
~ibp-registry~ database ends at that date.

** Disorder to study

Next, we need to define what the earliest age of onset we want to use for
the disorder. Since we are studying schizophrenia, we are going to use 10:

#+BEGIN_SRC R :exports code
earliest_onset_age <- 10
#+END_SRC

#+RESULTS:
: 10

** Cohort to estimate the risk in

Next we define the millenials period (1981 to 1996) as the allowed date of birth:

#+BEGIN_SRC R :exports code
born_at_start <- as.Date("1981-01-01")
born_at_end   <- as.Date("1996-01-01")
#+END_SRC

#+RESULTS:
: 1996-01-01

* Data processing

Now that we have defined all arguments to use, it's time to read and process the
TTE data that we are going to analyze. The TTE data needs to fulfill the following
requirements in order to be used by this pipeline:

1. Each row represents an individual
2. Each individual can only appear once
3. The following columns *must* exist:
   - person_id :: A combination of letters/numbers that uniquely identifies an individual
   - failure_status :: Non-negative integer that can be 0, 1 or 2:
     - 0 :: Censoring
     - 1 :: Affected by disorder
     - 2 :: Competing risk
   - failure_time :: Non-negative integer that represents the age of the individual when the failure/event occured
4. Can contain any other column used in pre-analysis filtering

Since we are only studying millenials, our TTE data also needs to contain a column that
contains each individuals birth date. In this guide, we call this column ~born_at~.
The file format of the data is not important, what is important is that we can read the
data and convert into a ~data.table~.

The example data in this guide is contained in a file called ~tte_SCZ.csv~,
so we simply read it and convert it into a ~data.table~:

#+BEGIN_SRC R :eval no :exports code
tte <- read_csv("./tte_SCZ.csv") |> as.data.table()
#+END_SRC

#+BEGIN_SRC R :exports results :results output :tangle no
set.seed(6)
n_count <- 100000

tte <- generate_random_tte(n_count)
tte <- generate_failure(tte, 20, 10) |>
  select(-born_at_year, -dead_at_year, -relatives) |>
  as.data.table()
#+END_SRC

#+RESULTS:

Note that the example data in this guide contains 100000 randomly generated individuals:

- Born between ~1890-01-01~ and todays date
- Age of death from normal distribution, mean = ~68~, sd = ~8.2~
- Age of onset from normal distribution, mean = ~20~, sd = ~10~
- If death appears after study end, the following probablities of ~failure_status~:
  - censored (0) :: ~0.9~
  - affected (1) :: ~0.1~
- If death appears before study end, the following probablities of ~failure_status~:
  - affected (1) :: ~0.1~
  - competing risk (2) :: ~0.9~

After the data has been read, we need to apply our millenials filter to it:

#+BEGIN_SRC R :exports both :results output
tte <- tte |>
  filter(
    born_at >= born_at_start,
    born_at <= born_at_end
  )
#+END_SRC

#+RESULTS:

Here's what the filtered data looks like, note that we have less than 100000 individuals now
that we have filtered out non-millenials:

#+BEGIN_SRC R :exports both :results output
print(tte)
#+END_SRC

#+RESULTS:
#+begin_example
       person_id    born_at failure_status failure_time
    1:        12 1995-12-01              0           29
    2:        14 1981-11-29              0           43
    3:        16 1985-12-24              0           39
    4:        19 1993-02-14              0           31
    5:        20 1993-08-20              0           31
   ---
20249:     99990 1995-10-07              0           29
20250:     99992 1984-01-09              1           38
20251:     99997 1994-06-04              0           30
20252:     99999 1992-07-21              0           32
20253:    100000 1993-09-03              1            1
#+end_example

* Analysis

Now that we have the TTE data for schizophrenia in millenials, we can run the
actual analysis. Since we are going to produce cumulative incidence risk estimates,
we will use the class ~CumulativeIncidenceAnalysis~. We start out by creating the
instance:

#+BEGIN_SRC R :exports code
cif_analysis <- CumulativeIncidenceAnalysis$new()
#+END_SRC

#+RESULTS:

This class defaults to the age of onset range 1 to 100 years. In our case, we
want to use the range 10 to 100 years, therefor we need to provide both
the TTE data and the earliest onset age:

#+BEGIN_SRC R :exports code :results output
estimates <- cif_analysis$run(
  tte = tte,
  earliest_onset_age = earliest_onset_age
)
#+END_SRC

#+RESULTS:

And here's what the produced data looks like:

#+BEGIN_SRC R :exports both :results output
print(estimates)
#+END_SRC

#+RESULTS:
#+begin_example
    time    estimate     variance         l95         u95 cases
 1:    1 0.002468770 1.216016e-07 0.001785303 0.003152237    21
 2:    2 0.003505653 1.724948e-07 0.002691632 0.004319675    37
 3:    3 0.004295660 2.111993e-07 0.003394931 0.005196389    56
 4:    4 0.005233793 2.570808e-07 0.004240029 0.006227556    70
 5:    5 0.005925048 2.908326e-07 0.004868061 0.006982035    99
 6:    6 0.007356935 3.605970e-07 0.006179982 0.008533888   130
 7:    7 0.008887572 4.349489e-07 0.007594963 0.010180181   164
 8:    8 0.010566336 5.162300e-07 0.009158118 0.011974553   197
 9:    9 0.012195724 5.948544e-07 0.010684066 0.013707382   247
10:   10 0.014664494 7.134827e-07 0.013008954 0.016320035   294
11:   11 0.016985138 8.244445e-07 0.015205512 0.018764764   333
12:   12 0.018910779 9.161154e-07 0.017034820 0.020786737   387
13:   13 0.021577050 1.042440e-06 0.019575928 0.023578172   455
14:   14 0.024934578 1.200516e-06 0.022787083 0.027082073   528
15:   15 0.028538982 1.368977e-06 0.026245759 0.030832204   588
16:   16 0.031501506 1.506478e-06 0.029095873 0.033907139   667
17:   17 0.035402163 1.686198e-06 0.032857077 0.037947248   738
18:   18 0.038907816 1.846437e-06 0.036244546 0.041571087   822
19:   19 0.043055350 2.034447e-06 0.040259774 0.045850926   899
20:   20 0.046857256 2.205298e-06 0.043946661 0.049767851   984
21:   21 0.051054165 2.392243e-06 0.048022713 0.054085617  1076
22:   22 0.055596702 2.592622e-06 0.052440842 0.058752561  1162
23:   23 0.059842986 2.778090e-06 0.056576196 0.063109777  1238
24:   24 0.063595517 2.940511e-06 0.060234587 0.066956447  1313
25:   25 0.067298672 3.099431e-06 0.063848116 0.070749228  1386
26:   26 0.070903076 3.252812e-06 0.067368173 0.074437980  1459
27:   27 0.074507480 3.404910e-06 0.070890877 0.078124084  1531
28:   28 0.078062509 3.553669e-06 0.074367746 0.081757272  1580
29:   29 0.080481904 3.654193e-06 0.076735248 0.084228560  1668
30:   30 0.084827873 3.833360e-06 0.080990465 0.088665280  1728
31:   31 0.088000413 3.974007e-06 0.084093242 0.091907584  1787
32:   32 0.091366988 4.136123e-06 0.087380919 0.095353058  1836
33:   33 0.094386522 4.294146e-06 0.090325021 0.098448022  1878
34:   34 0.097209423 4.456572e-06 0.093071822 0.101347023  1909
35:   35 0.099502459 4.603159e-06 0.095297361 0.103707556  1937
36:   36 0.101795468 4.767067e-06 0.097516159 0.106074778  1963
37:   37 0.104168773 4.957995e-06 0.099804608 0.108532938  1969
38:   38 0.104792538 5.015903e-06 0.100402962 0.109182115  1988
39:   39 0.107097005 5.268933e-06 0.102598073 0.111595938  1992
40:   40 0.107680630 5.347160e-06 0.103148423 0.112212836  1998
41:   41 0.108772025 5.532410e-06 0.104161979 0.113382070  2001
42:   43 0.109500265 5.700054e-06 0.104820893 0.114179637  2003
    time    estimate     variance         l95         u95 cases
#+end_example

* Next steps

The next natural step would be to estimate heritability for the disorder, since
cumulative incidence is used as inputs to the heritability calculation.

Heritability is done using the ~HeritabilityAnalysis~ class of this package. You
can either:

- Read the [[../heritability/index.org][reference documentation of ~HeritabilityAnalysis~]]
- Read the [[../heritability/guide.org][guide on how to estimate heritability for a single disorder]]
- Read the [[../heritability/guide-yob.org][guide on how to estimate heritability for a single disorder, stratified by birth year]]
